<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace dmstr\modules\prototype\controllers\base;

use dmstr\bootstrap\Tabs;
use dmstr\modules\prototype\assets\AccessTrackingAsset;
use dmstr\modules\prototype\models\Less;
use dmstr\modules\prototype\models\search\Less as LessSearch;
use Exception;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\HttpException;

/**
 * LessController implements the CRUD actions for Less model.
 */
class LessController extends Controller
{
    /**
     * @var boolean whether to enable CSRF validation for the actions in this controller.
     * CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
     */
    public $enableCsrfValidation = false;


    /**
     * Lists all Less models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LessSearch;
        $dataProvider = $searchModel->search($_GET);

        Tabs::clearLocalStorage();
        Yii::$app->session['__crudReturnUrl'] = null;

        return $this->render(
            'index',
            [
                'dataProvider' => $dataProvider,
                'searchModel' => $searchModel,
            ]
        );
    }

    /**
     * Displays a single Less model.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render(
            'view',
            [
                'model' => $this->findModel($id),
            ]
        );
    }

    /**
     * Creates a new Less model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Less;

        try {
            if ($model->load($_POST) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } elseif (!Yii::$app->request->isPost) {
                $model->load($_GET);
            }
        } catch (Exception $e) {
            $msg = (isset($e->errorInfo[2])) ? $e->errorInfo[2] : $e->getMessage();
            $model->addError('_exception', $msg);
        }
        return $this->render('create', ['model' => $model]);
    }

    /**
     * Updates an existing Less model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if (!Yii::$app->getUser()->getIsGuest()) {
            $model->addUserToAccessList(Yii::$app->getUser()->getId());
        }
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->addFlash('success', 'Record has been updated');

            if ($this->module->enableLessLinting) {
                if (Yii::$app->request->post('subaction') === 'lint') {
                    $model->lintLess();
                    if (empty($model->lintErrors)) {
                        return $this->refresh();
                    }
                }
                if (Yii::$app->request->post('subaction') === 'fix') {
                    $model->lintLess(true);
                    $model->value = $model->fixedValue;
                    if ($model->save()) {
                        return $this->refresh();
                    }
                }
            }

            if (Yii::$app->request->post('subaction') === 'save') {
                return $this->redirect(['index']);
            }
        }

        AccessTrackingAsset::register($this->view);
        return $this->render(
            'update',
            [
                'model' => $model,
            ]
        );
    }

    /**
     * Deletes an existing Less model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionDelete($id)
    {
        try {
            if ($this->findModel($id)->delete()) {
                Yii::$app->getSession()->addFlash('info', "Record #$id deleted");
            }
        } catch (Exception $e) {
            $msg = (isset($e->errorInfo[2])) ? $e->errorInfo[2] : $e->getMessage();
            Yii::$app->getSession()->addFlash('error', $msg);
        }

        return $this->redirect('index');
    }

    /**
     * Finds the Less model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id
     *
     * @return Less the loaded model
     * @throws HttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Less::findOne($id)) !== null) {
            return $model;
        } else {
            throw new HttpException(404, 'The requested page does not exist.');
        }
    }
}
